### ISSUE TITLE
Question about GTA5 dataset training list

### ISSUE THREAD

**Issue by krumo** [yzou2/CRST#1]
Hi, thanks for your impressive work. 

I have a question regarding the list of GTA5 training set. As far as I know, GTA5 dataset has about 25k images, while in the training list you provide at [here](https://github.com/yzou2/CRST/blob/master/dataset/list/gta5/train.lst), there are only about 20k lines, which means that about 5k images are filtered out for training. Would you like to spend some time explaining how do you get this list and why several images are missing? Thanks in advance!

**Comment by yzou2** [comment]
Thanks for your interests in our work. 

To answer your questions, we notice there are lots of GTA5 images not realistic for driving scenes, e.g. cars driving on sidewalk, car roll over, etc. See the attached images as examples. We use a simple algorithm to automatically filter these images out. The basic idea is to calculate the statistics of road pixels in a center bottom patch. If road pixels are dominating in the patch, the images will be remained. If sidewalk pixels dominating, the images will be filtered out. Hope this answer your question.

![13017](https://user-images.githubusercontent.com/20036855/66800470-412d8580-eee3-11e9-876d-a62afceb6175.png)
![13016](https://user-images.githubusercontent.com/20036855/66800485-4be81a80-eee3-11e9-861e-cfa95df312e2.png)
![13013](https://user-images.githubusercontent.com/20036855/66800492-5a363680-eee3-11e9-823e-f2b077bb95a7.png)
![13011](https://user-images.githubusercontent.com/20036855/66800506-61f5db00-eee3-11e9-95c9-76108c873bdc.png)

**Comment by krumo** [comment]
@yzou2 Thanks for your detailed explanation! Your answer totally solves my question.
