### ISSUE TITLE
problem about new dataset label convert

### ISSUE THREAD

**Issue by qiaozhuocheng** [yzou2/CRST#10]
Hello,  I trained a model  based on  synthia dataset and the label noted in labels_synthia.py . But when I evaluate the model with cityscapes and the label from labels.py , I found the result is absolutely wrong. Do you know what step is wrong?
![frankfurt_000001_057181_leftImg8bit_color](https://user-images.githubusercontent.com/50092281/69163606-7acc5e80-0b29-11ea-9844-2e027c5864bc.png)
By the way , I change the datasets.py as follow to read the label in synthia because cv2 couldn't read the label in one channel.

SYNTHIA_label_map = {3: 0, 4: 1, 2: 2, 21: 3, 5: 4, 7: 5, 15: 6, 9: 7, 6: 8, 1: 9, 10: 10, 17: 11, 8: 12, 19: 13, 12: 14, 11: 15}
#image_size = (640, 360)
def get_label_set(input):
    reshape_list = list(np.reshape(input,(-1,)))
    label_set = set(reshape_list)
    return label_set

def read_SYNTHIA_label(label_path, kv_map):
    raw_label = cv2.imread(label_path,-1)
    raw_label_p = raw_label[:, :, -1]
    label = raw_label_p
    label_copy = 255 * np.ones(label.shape, dtype=np.float32)
    for k, v in kv_map.items():
        label_copy[label == k] = v #others are turned to 255
    return label_copy
label = np.array(read_SYNTHIA_label(datafiles["label"], SYNTHIA_label_map), dtype=np.uint8)

**Comment by yzou2** [comment]
Actually, I have uploaded the dataloader for synthia only training in deeplab/datasets.py. SYNTHIADataSet is for training on SYNTHIA only. SYNTHIADataSet already handle the label mapping.

For self-training, I think you can use the default dataloaders as GTA2Cityscapes. These dataloaders can automatically handle the mapping for loading source (synthia) and target (cityscapes) in re-training part. But you need to change the mapping in the crst_seg.py as follows. Notet that here the mapping is used to convert the trainID for test and evaluation. 

###################################

    ## label mapping
    sys.path.insert(0, 'dataset/helpers')
    if args.data_src == 'synthia':
        from labels_cityscapes_synthia import id2label, trainId2label
    elif args.data_src == 'gta':
        from labels import id2label, trainId2label
    label_2_id = 255 * np.ones((256,))
    for l in id2label:
        if l in (-1, 255):
            continue
        label_2_id[l] = id2label[l].trainId
    id_2_label = np.array([trainId2label[_].id for _ in trainId2label if _ not in (-1, 255)])
    valid_labels = sorted(set(id_2_label.ravel()))

###################################


I also post the palette you may find useful:

# palette
if args.data_src == 'gta':
    # gta:
    palette = [128, 64, 128, 244, 35, 232, 70, 70, 70, 102, 102, 156, 190, 153, 153, 153, 153, 153, 250, 170, 30,
               220, 220, 0, 107, 142, 35, 152, 251, 152, 70, 130, 180, 220, 20, 60, 255, 0, 0, 0, 0, 142, 0, 0, 70,
               0, 60, 100, 0, 80, 100, 0, 0, 230, 119, 11, 32]
elif args.data_src == 'synthia':
    # synthia:
    palette = [128,64,128,244,35,232,70,70,70,102,102,156,64,64,128,153,153,153,250,170,30,220,220,0,
                107,142,35,70,130,180,220,20,60,255,0,0,0,0,142,0,60,100,0,0,230,119,11,32]
