### ISSUE TITLE
ResNet-38 for CRST

### ISSUE THREAD

**Issue by dlsrbgg33** [yzou2/CRST#13]
Hi, Thank you for your great work and contribution.
I am in the middle of reproducing your work with proposed backbones. 
Is there a PyTorch based initial ResNet-38 model that is pre-trained on GTA and SYNTHIA to get the paper results?
Thank you again, and I hope I get a positive response.

**Comment by yzou2** [comment]
Thanks a lot for your interests in our work. Unfortunately we only implemented ResNet-38 with MxNet in our CBST repo (check https://github.com/yzou2/CBST). But you may want to train Pytorch ResNet-38 model based on https://github.com/mapillary/inplace_abn

**Comment by dlsrbgg33** [comment]
Thank you for your prompt reply. I'll try with that
