### ISSUE TITLE
strange result??

### ISSUE THREAD

**Issue by MyeongJin-Kim** [yzou2/CRST#17]
When I run your crst.seg with src-model using mrkld.sh, after training with pseudo label, iou drop drastically.

<img width="813" alt="image" src="https://user-images.githubusercontent.com/39029444/72961285-de0d9200-3df3-11ea-9073-e2874a1ecacb.png">

**Comment by yzou2** [comment]
Can you provide more details and configuration about your experiment? Then I can help to debug. You may want to check the generated pseudo labels in first two rounds.

**Comment by MyeongJin-Kim** [comment]
When I check generated pseudo label, color of classes seems strange

<img width="1188" alt="image" src="https://user-images.githubusercontent.com/39029444/72961717-680a2a80-3df5-11ea-863f-4065c4086df2.png">

**Comment by yzou2** [comment]
Did you use correct label mapping function for generating pseudo label?

**Comment by MyeongJin-Kim** [comment]
I didn't change any code about generating pseudo label

**Comment by yzou2** [comment]
In my computer, the results are good. What's your configuration (pytorch version, etc)? Can you show me the predictions and pseudo label in the initial round? Your pseudo label map seems incorrect.

**Comment by MyeongJin-Kim** [comment]
I used pytorch 1.2 and python 3.6

This initial pseudo label (0) seems right.
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/39029444/73054018-afafb580-3ecc-11ea-9d5c-5698aeac2573.png">

This is same image's  pseudo label (1). it seems wrong.
<img width="1202" alt="image" src="https://user-images.githubusercontent.com/39029444/73054089-da017300-3ecc-11ea-85ef-e9fb32021812.png">

**Comment by yzou2** [comment]
As mentioned in requirement, the code is implemented based on Pytorch 0.4.0 with CUDA 9.0, OpenCV 3.2.0 and Python 2.7.12. Running code in other version gives different result.

**Comment by singformiku** [comment]
Hi, may I ask why different version would cause iou drop drastically?
Since I have same issue as @MyeongJin-Kim.

Sincerely, Paul

**Comment by yzou2** [comment]
> Hi, may I ask why different version would cause iou drop drastically?
> Since I have same issue as @MyeongJin-Kim.
> 
> Sincerely, Paul

In my opinions, its' due to the difference between implementations of operations/optimization across pytorch versions. But to be honest, I did not dive deep into it. If you have any insights or discovery, I would be very glad to hear that. : )

**Comment by singformiku** [comment]
Thanks for the reply,
I have one more question
Can you show me your pseudo labels results about "aachen_000010_000019_leftImg8bit.png" in epoch 0 & 1? 
I am curious what the correct pseudo labels actually look like.
