### ISSUE TITLE
Memoryerror

### ISSUE THREAD

**Issue by qiaozhuocheng** [yzou2/CRST#2]
Hello,I am very interested about your project.But when I started cbst with gta2cityscapes,something was wrong.It shows cuda out of memory.And when I set batch_size =1,--mine-chance 0.0,another memoryerror happens as follow:
traceback (most recent call last):
  File "crst_seg.py", line 954, in <module>
    main()
  File "crst_seg.py", line 327, in main
    label_2_id, valid_labels, args, logger)
  File "crst_seg.py", line 464, in val
    output = 0.5 * ( output + softmax2d(interp(output2)).cpu().data[0].numpy()[:,:,::-1] )
MemoryError
MY cpu Intel(R) Core(TM) i3-8100 CPU @ 3.60GHz
gpu GeForce GTX 1080ti
cuda8,pytorch 0.4.0
python 2.7.16

**Comment by yzou2** [comment]
Since 1080ti has 11 GB memory and my default setting will take more than 11 GB memory, I wonder if the memory error is caused by this. You can try to reduce the '--input-size' to smaller size (480, 960), that may help.

**Comment by qiaozhuocheng** [comment]
Thank you for your prompt reply.I change the input size as you suggested and the memory error not  happened, but after several hours training it ceased without error mention ,only 'killed'.

2019-11-05 16:28:04,774 Host Done 394/500 with speed: 0.18/s
2019-11-05 16:28:04,825 Host mean iou: 44.69%
2019-11-05 16:28:04,883 Host 
[91.52 56.62 78.72 29.44 20.57 40.52 26.34 17.22 83.67 31.70 73.01 63.21
 24.39 81.54 27.58 30.62  0.44 29.42 42.53]
Killed

I think it's not the signal of successfully finished ,right?

**Comment by yzou2** [comment]
The code works well in my desktops and servers. Are there any other programs occupying your GPUs?

**Comment by qiaozhuocheng** [comment]
No other program,and I only change the input size as you suggest.

**Comment by qiaozhuocheng** [comment]
I found that it's because high burden of my cpu, so what parameters can I change to reduce the high occupation of cpu memory
![image](https://user-images.githubusercontent.com/50092281/68392898-c421c300-01a5-11ea-8d28-f5828b993439.png)

**Comment by yzou2** [comment]
I think the most cpu intensive cost part in the code is confidence sorting. You may considering set --ds-rate to 6/8/10 to increase the downsampling rate. You may also play with num_worker in dataloader (Line 370), try 1/2, etc

**Comment by qiaozhuocheng** [comment]
I am sorry , but the problem still occurred.  I can successfully run your another MXNET based CBST project , so is any params you changed supposed will lead this bug?

**Comment by yzou2** [comment]
> I am sorry , but the problem still occurred. I can successfully run your another MXNET based CBST project , so is any params you changed supposed will lead this bug?

Which stage did this program shutting down happen? Evaluation, pseudo-label generation, network retraining? If in pseudo-label generation, you may still increase the downsampling rate --ds-rate to 16.

BTW, what's your memory size?

**Comment by qiaozhuocheng** [comment]
2019-11-10 01:06:20,835 Host Done 302/500 with speed: 0.17/s
2019-11-10 01:06:20,835 Host mean iou: 32.63%
2019-11-10 01:06:20,924 Host 
[72.10 30.08 66.78  4.26  9.86 35.71 23.61 21.61 77.59 12.45 71.39 47.72
 13.27 75.90 10.41 30.89  0.04 16.23  0.00]
Killed
evaluation stage,and my memory is 16g

**Comment by yzou2** [comment]
Maybe you can try disenable multi scale testing, set --test-scale to 0.9

**Comment by qiaozhuocheng** [comment]
It works, thank you!
