### ISSUE TITLE
Resizing cityscape

### ISSUE THREAD

**Issue by singformiku** [yzou2/CRST#21]
Hi, The work is impressive. I have a queation about resizing cityscape. Should I resize cityscape into 1052x1914 just same as GTA5 do. According to the guidance you only inform us to resize GTA5.

**Comment by yzou2** [comment]
You don't need to resize Cityscapes. My code can handle the different size problem across datasets.

**Comment by singformiku** [comment]
Thanks for your advice!!

Sincerely, Paul


yzou2 <notifications@github.com> 於 2020年3月18日 週三 上午11:17寫道：
