### ISSUE TITLE
Trained model for round1 and round2 in CBST

### ISSUE THREAD

**Issue by YanLiang0813** [yzou2/CRST#26]
Hi, thanks for your code. Could you provide the trained model for round1 and round2 in CBST? I want to use those models to generate pseudo labels.  Thanks!!

**Comment by yzou2** [comment]
This is the models of mrkld.

https://www.dropbox.com/s/xr7fc8fyprfpjwn/mrkld_models.zip?dl=0

**Comment by yzou2** [comment]
This is the link to models of cbst.

https://www.dropbox.com/s/hf5w9rkueemhp3i/cbst.zip?dl=0

**Comment by YanLiang0813** [comment]
Thanks for your reply!




    


On 07/08/2020 07:17, yzou2 wrote: 
This is the link to models of cbst.
https://www.dropbox.com/s/hf5w9rkueemhp3i/cbst.zip?dl=0

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/yzou2/CRST/issues/26#issuecomment-655187468",
"url": "https://github.com/yzou2/CRST/issues/26#issuecomment-655187468",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
