### ISSUE TITLE
Cityscape and GTA Dataset

### ISSUE THREAD

**Issue by RamyaRaghuraman** [yzou2/CRST#3]
Hi @yzou2 ,

Really nice work!
Just wanted to make sure I am working with the right dataset, we need :
1)gtFine_trainvaltest and leftImg8bit_trainvaltest from cityscapes and
2)all the 10 parts from the GTA dataset (24966 images)?

**Comment by yzou2** [comment]
> Hi @yzou2 ,
> 
> Really nice work!
> Just wanted to make sure I am working with the right dataset, we need :
> 1)gtFine_trainvaltest and leftImg8bit_trainvaltest from cityscapes and
> 2)all the 10 parts from the GTA dataset (24966 images)?

Hi Ramya, thanks a lot for your interests. You are right. Note that for cityscapes, just use train set for training and val set for testing.
