### ISSUE TITLE
About dataset/list/gta5/train.lst & val.lst

### ISSUE THREAD

**Issue by YoNyeoSeok** [yzou2/CRST#32]
Hi.
I am wondering why 19,984 images are in the gta5 train and val list, rather than 24,966 images.
Why 4,982 images are removed?
Thanks.

**Comment by tht106** [comment]
Hello, you may refer to #1.

**Comment by yzou2** [comment]
> Hello, you may refer to #1.

Thanks, @tht106 . Just check https://github.com/yzou2/CRST/issues/1

**Comment by YoNyeoSeok** [comment]
Thank you so much!!
