### ISSUE TITLE
How to train our own dataset?

### ISSUE THREAD

**Issue by lovekenturkey** [yzou2/CRST#9]
I want use synthetic dataset as source dataset ,and I change the path  and train list.
  File "/home/qiu/下载/CRST-master/deeplab/datasets.py", line 178, in __getitem__
    img_h, img_w = label.shape
ValueError: too many values to unpack
SO is the dataset must be the same size as gta5 or some params need change?

**Comment by yzou2** [comment]
Of course not. too many values to unpack means you have more than 2 outputs. Check your label to see if it contains 3 channels.

**Comment by yzou2** [comment]
If 3, just set    img_h, img_w, _ = label.shape
